# Generated by Django 4.0.3 on 2022-05-23 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0003_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='stNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Political Science', 'Political Science'), ('Sociology', 'Sociology'), ('Socialwork', 'Social Work'), ('Health and Body', 'Health and Body'), ('Computer Science', 'Computer Science'), ('Information Technology', 'Information Technology'), ('Managerial Studies', 'Managemerial Studies'), ('Accountancy', 'Accountancy'), ('Economics', 'Economics'), ('English Literature', 'English Literature'), ('English Grammar', 'English Grammar'), ('Maths', 'Maths'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('Geology', 'Geology'), ('Physics', 'Physics'), ('Astronomy', 'Astronomy'), ('Architectural and Structural', 'Architectural and Sructural'), ('Food and Hospitality', 'Food and Hospitality')], default='Information Technology', max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('files', models.FileField(blank=True, null=True, upload_to='fileuploads')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
